# Generated by Django 4.1.3 on 2022-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_deploy_history',
            fields=[
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('revision', models.CharField(max_length=100)),
                ('deploy_type', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=100)),
                ('insert_dt', models.DateTimeField()),
                ('manager_id', models.CharField(max_length=100)),
                ('manager_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
