# Generated by Django 4.1.3 on 2022-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_deploy_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_deploy_history',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app_deploy_history',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
