# Generated by Django 4.1.3 on 2022-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='bearer_token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
