# Generated by Django 4.1.3 on 2022-11-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_cluster_bearer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='cluster_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
