# Generated by Django 4.1.3 on 2022-11-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_alter_cluster_cluster_type_alter_cluster_cluster_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kubeconfig',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
