# Generated by Django 4.1.3 on 2022-11-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_alter_cluster_kubeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='kubeconfig',
            field=models.FileField(default=1, upload_to='kube_config'),
            preserve_default=False,
        ),
    ]
