# Generated by Django 4.1.3 on 2022-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcreate',
            fields=[
                ('appname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cn_img', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=20)),
                ('kube_cfg', models.CharField(max_length=100)),
                ('kube_mani', models.TextField()),
                ('repo_url', models.TextField()),
                ('ins_date', models.DateTimeField()),
                ('ins_id', models.CharField(max_length=100)),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('up_id', models.CharField(max_length=100)),
            ],
        ),
    ]
