# Generated by Django 4.0.5 on 2022-11-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hpadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=100)),
                ('container', models.CharField(max_length=100)),
                ('hpa', models.CharField(max_length=20)),
                ('maxcpu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maxram', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minrep', models.IntegerField()),
                ('maxrep', models.IntegerField()),
                ('autosche', models.BooleanField()),
                ('promql', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
