# Generated by Django 4.1.3 on 2022-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcreate',
            fields=[
                ('app_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=100)),
                ('namespace', models.CharField(max_length=100)),
                ('repo_url', models.TextField()),
                ('target_revision', models.TextField()),
                ('target_path', models.TextField()),
                ('insert_dt', models.DateTimeField()),
                ('insert_user', models.CharField(max_length=100)),
                ('update_dt', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=100)),
            ],
        ),
    ]
