# Generated by Django 4.1.3 on 2022-11-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_appcreate_update_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreate',
            name='cluster_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
