# Generated by Django 4.1.3 on 2022-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_appcreate_cluster_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcreate',
            name='insert_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
